models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def init_app(app):
    print(app.config["SQLALCHEMY_DATABASE_URI"])
    db.init_app(app)
    with app.app_context():
        db.create_all()


# MONGODB_DB = "lawdb"

# db = MongoEngine()


# def init_db(app):
#     db.init_app(app)


# def init_mongoengine(settings):
#     import mongoengine as me

#     dbname = settings.get("MONGODB_DB")
#     host = settings.get("MONGODB_HOST", "localhost")
#     port = int(settings.get("MONGODB_PORT", "27017"))
#     username = settings.get("MONGODB_USERNAME", "")
#     password = settings.get("MONGODB_PASSWORD", "")

#     me.connect(db=dbname, host=host, port=port, username=username, password=password)

models/messeges.py
from . import db


class Messege(db.Model):
    id = db.Column(
        db.BigInteger().with_variant(db.Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    description = db.Column(db.String)
    topic = db.Column(db.String)
    created_by = db.Column(db.String)

    created_date = db.Column(db.DateTime)


# class Messege(me.Document):
#     meta = {"collection": "messeges"}
#     description = me.StringField(required=True, max_length=256)
#     topic = me.ReferenceField("Topic", dbref=True)
#     created_by = me.StringField(required=True, max_length=256)

#     created_date = me.DateTimeField(required=True, default=datetime.datetime.now)

models/topics.py
from . import db


class Topic(db.Model):
    id = db.Column(
        db.BigInteger().with_variant(db.Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    name = db.Column(db.String)

    created_date = db.Column(db.DateTime)


# class Topic(me.Document):
#     meta = {"collection": "topics"}
#     name = me.StringField(required=True, max_length=256)
#     creted_by = me.StringField(required=True, max_length=256)
#     created_date = me.DateTimeField(required=True, default=datetime.datetime.now)

forms/messeges.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import validators
from wtforms import widgets


class MessegeForm(FlaskForm):

    description = StringField("พิมพ์ข้อความ", validators=[validators.DataRequired()])

main.py
from flask import Flask, render_template, redirect, url_for
from flask_login import LoginManager

from views import messeges
import models


import os
from flask import Flask
from flask_pymongo import PyMongo


login_manager = LoginManager()
login_manager.login_view = "accounts.login"


# @login_manager.unauthorized_handler
# def unauthorized():
#     # do stuff
#     # return "You don't have permission"
#     print("You don't have permission")
#     return redirect(url_for("accounts.login"))

app = Flask(__name__)


@login_manager.user_loader
def load_user(user_id):
    user = None
    return user


@app.route("/")
def index():
    return render_template("main/index.html")


if __name__ == "__main__":
    app.secret_key = "123456"  # import os // os.get_env['SECRET_KEY']
    login_manager.init_app(app)

    # app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///:memory"
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{os.getcwd()}/db/project.db"
    models.init_app(app)

    app.register_blueprint(messeges.bp)

    app.run(debug=True)
    # app.config["MONGO_URI"] = "mongodb://localhost:27017/lawai"
    # mongo = PyMongo(app)

views/messeges.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, login_user, logout_user

from werkzeug.security import generate_password_hash, check_password_hash

from forms import messeges as ms

import datetime
import models
from models.messeges import Messege
from models.topics import Topic
from openai import OpenAI
import openai
import os

client = OpenAI(
    api_key= "YOUR_OPENAI_API"
)

bp = Blueprint("messeges", __name__, url_prefix="/messeges")


def get_answer(text, topic_name):
    completion = client.chat.completions.create(
        model="YOUR_MODEL_MODEL",
        max_tokens=1024,
        temperature=0.2,
        messages=[
            {"role": "system", "content": "คุณคือนักกฎหมายที่เชี่ยวชาญด้านการจัดซื้อจัดจ้างภาครัฐ"},
            {"role": "user", "content": f"คำถาม: {text} เรื่อง การจัดซื้อจัดจ้างภาครัฐ"}
        ]
    )

    messege = Messege()
    
    messege.description = f"{completion.choices[0].message.content}"
    messege.topic = topic_name
    messege.created_by = "Ai"
    messege.created_date = datetime.datetime.now()
    models.db.session.add(messege)
    models.db.session.commit()


@bp.route(
    "/",
    methods=["GET", "POST"],
    defaults={"topic_name": None},
)
@bp.route("/<topic_name>/", methods=["GET", "POST"])
def index(topic_name):

    messeges = None
    if topic_name:
        messeges = models.db.session.query(Messege).filter_by(topic=topic_name)
    # if topic_name:
    #     messeges = Messege.objects(topic=topic_obj)

    # topics = Topic.objects()

    # print("------------>", topics)

    print("------------>", messeges)
    topics = models.db.session.query(Topic)

    form = ms.MessegeForm()
    if not form.validate_on_submit():
        print(form.errors)
        return render_template(
            "/messeges/index.html",
            form=form,
            messeges=messeges,
            topics=topics,
        )

    messege = Messege()
    form.populate_obj(messege)
    messege.created_by = "User"
    messege.created_date = datetime.datetime.now()

    if not topic_name:

        topic = Topic()
        order = (
            models.db.session.query(Topic.name)
            .filter_by(name=form.description.data)
            .first()
        )
        print(order)
        if order:
            topic.name = form.description.data + " " + str(len(order))
            messege.topic = form.description.data + " " + str(len(order))
        else:
            topic.name = form.description.data
            messege.topic = form.description.data
        topic.created_date = datetime.datetime.now()
        models.db.session.add(topic)
        models.db.session.commit()
        topic_name = topic.name
    else:
        messege.topic = topic_name
        topic_name = topic_name

    models.db.session.add(messege)
    models.db.session.commit()
    if form.description.data:
        get_answer(form.description.data, topic_name)

    return redirect(url_for("messeges.index", topic_name=topic_name))


@bp.route("/<topic_id>/delete")
def delete(topic_id):
    topic = models.db.session.query(Topic).filter_by(id=topic_id).first()
    messeges = models.db.session.query(Messege).filter_by(topic=topic.name)
    for ms in messeges:
        models.db.session.delete(ms)
        models.db.session.commit()

    models.db.session.delete(topic)
    models.db.session.commit()

    return redirect(url_for("messeges.index"))

templates/main/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>LAW</title>
    <link rel="stylesheet" href="https://kit.fontawesome.com/eab4031eed.css" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/eab4031eed.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </head>
<style>
  .main-wrapper {
    height: 100%;  
  }
</style>
<body style=" background-image: url('/static/top-view-career-guidance-items-judges.jpg'); height:90vh; background-size: cover;">
  <div class="main-wrapper h-100 ">
    <nav class="navbar"  style="background-color: #5C391F; height:7vh;">
    </nav>
    <div style="height:80%;">
      <div class="row d-flex justify-content-center" style="padding-top:30vh; width:100%">
        <div class="d-flex justify-content-center">
          <p class="fs-1">
              มาตรากฎหมาย
          </p>
        </div>
        <div class="d-grid gap-2 col-6 mx-auto">
          <a class="btn btn-outline-success" type="button" href="{{ url_for('messeges.index') }}">Go to website</a>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

templates/messeges/index.html
<!DOCTYPE html>
<html>

<head>
  <title>LAW</title>
  <link rel="stylesheet" href="https://kit.fontawesome.com/eab4031eed.css" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/eab4031eed.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>
</head>
<style>
  .chat-online {
    color: #34ce57
  }

  .chat-offline {
    color: #e4606d
  }

  .chat-messages {
    display: flex;
    flex-direction: column;
    padding-top: 20;
  }

  .chat-message-left,
  .chat-message-right {
    display: flex;
    flex-shrink: 0
  }

  .chat-message-left {
    margin-right: auto
  }

  .chat-message-right {
    flex-direction: row-reverse;
    margin-left: auto
  }

  .py-3 {
    padding-top: 1rem !important;
    padding-bottom: 1rem !important;
  }

  .px-4 {
    padding-right: 1.5rem !important;
    padding-left: 1.5rem !important;
  }

  .flex-grow-0 {
    flex-grow: 0 !important;
  }

  .border-top {
    border-top: 1px solid #dee2e6 !important;
  }
</style>

<body style="height:90vh; background-color: #D9D9D9;">
  <nav class="navbar position-fixed" style="background-color: #5C391F; height:8vh; width:100%">
    <button class="btn text-white " type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample"
      aria-controls="offcanvasExample">
      <h5><i class="fa-solid fa-bars" style="margin-right:1vw;"></i> มาตรากฎหมาย
      </h5>
    </button>
  </nav>
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel"
    style="background-color: #5C391F;">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title text-white" id="offcanvasExampleLabel"> มาตรากฎหมาย
        <a href="{{ url_for('messeges.index') }}" class="text-white" style="padding-left: 10px;"> <i
            class="fa-solid fa-plus"></i> </a>
      </h5>
      <button type="button" class="btn-close text-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      {% if topics %}
      {% for tp in topics %}
      <div class="d-flex justify-content-between border-bottom" style="padding-bottom: 10px; padding-top: 10px;">
        <a href="{{ url_for('messeges.index', topic_name=tp.name) }}" class=" text-decoration-none">
          <div class="d-flex w-100 align-items-center justify-content-between">
            <strong class="mb-1 text-white">{{ tp.name }}</strong>
          </div>
        </a>
        <div>
          <small class="text-white-50">{{ tp.created_date.strftime('%Y-%m-%d') }}
          </small>
          <a href="{{ url_for('messeges.delete', topic_id=tp.id) }}" class="text-white-50">
            <i class="fa-solid fa-trash"></i>
          </a>
        </div>

      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>

  <div class="d-flex flex-column-reverse"
    style="width:100%; padding-top:15vh; padding-left:10%; padding-right:10%; padding-bottom:10vh; background-color: #D9D9D9;">
    <div class="chat-messages p-4">
      {% if messeges %}

      {% for ms in messeges %}
      {% if ms.created_by == 'User' %}
      <div class="chat-message-right mb-4" style="padding-right:10px;">
        <div style="padding-left:10px;">
          <img src="/static/user.png" class="rounded-circle mr-1" alt="Chris Wood" width="40" height="40">
          <div class="text-muted small text-nowrap mt-2 text-center"> {{ ms.created_date.strftime('%Y-%m-%d') }}</br>
            {{ ms.created_date.strftime('%H:%M:%S') }} </div>
        </div>
        <div class="flex-shrink-1 bg-light rounded py-2 px-3 mr-3">
          <div class="font-weight-bold mb-1">You</div>
          {{ ms.description }}
        </div>
      </div>
      {% else %}
      <div class="chat-message-left pb-4">
        <div style="padding-right:10px;">
          <img src="/static/robot.png" class="rounded-circle mr-1" alt="Sharon Lessman" width="40" height="40">
          <div class="text-muted small text-nowrap mt-2 text-center"> {{ ms.created_date.strftime('%Y-%m-%d') }}</br>
            {{ ms.created_date.strftime('%H:%M:%S') }} </div>
        </div>
        <div class="flex-shrink-1 bg-light rounded py-2 px-3 ml-3">
          <div class="font-weight-bold mb-1"> Law Ai</div>
          {{ ms.description }}
        </div>
      </div>
      {% endif %}
      {% endfor %}
      {% endif %}

    </div>
  </div>

  <div class="position-fixed bottom-0 start-50 translate-middle-x" style="width:50vw">
    <form method="POST">
      <div class="input-group mb-3">
        {{ form.hidden_tag() }}
        {{ form.description(class_="form-control",placeholder="พิมพ์ข้อความ" )}}
        <button class="btn btn-outline-success" type="submit">ส่ง</button>
      </div>
    </form>
  </div>
</body>

</html>